[project]
name = "growth-mindset-challenge"
version = "0.1.0"
description = "Streamlit app for CSV/Excel data cleaning"
requires-python = ">=3.10,<3.13"

dependencies = [
    "streamlit",
    "pandas",
    "openpyxl",
    "xlsxwriter"
]
